image: node

cache:
  paths:
  - node_modules/
  key: "$CI_BUILD_REPO"

stages:
  - develop
  - staging
  - deploy

develop:
  stage: develop
  image: ruby:latest
  script:
   - gem install dpl
   - dpl --provider=heroku --app=$HEROKU_APP_DEV --api-key=$HEROKU_API_KEY
  except:
   - staging
   - master
   - 62-aft-configure-gitlab-ci-to-deploy-master-branch-in-firebase-hosting

staging:
  stage: staging
  image: ruby:latest
  script:
   - gem install dpl
   - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
   - staging

deploy:
  image: node:latest
  stage: deploy
  environment: Production
  only:
    - master
    - 62-aft-configure-gitlab-ci-to-deploy-master-branch-in-firebase-hosting
  script:
    - npm install -g firebase-tools
    - npm install -g bower
    - npm install
    - bower install --allow-root
    - firebase use --token $FIREBASE_TOKEN syshub-61377
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN

