image: node

cache:
  key: '$CI_BUILD_REPO'
  paths:
    - node_modules/

stages:
  - setup
  - build and deploy

Setup:
  stage: setup
  image: cortesa/docker-firebase:6.8.0
  script:
    - firebase --version
    - yarn install --pure-lockfile --cache-folder .yarn

Develop:
  stage: build and deploy
  image: cortesa/docker-firebase:6.8.0
  environment: development
  except:
    - master
    - production
  script:
    - yarn build:development
    - firebase use --token $FIREBASE_TOKEN syshub-dev
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN

Staging:
  stage: build and deploy
  image: cortesa/docker-firebase:6.8.0
  environment: development
  only:
    - master
  script:
    - yarn build:development
    - firebase use --token $FIREBASE_TOKEN syshub-dev
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN

# it should deploys in production
Production:
  stage: build and deploy
  image: cortesa/docker-firebase:6.8.0
  environment: production
  only:
    - production
  script:
    - yarn build:production
    - firebase use --token $FIREBASE_TOKEN syshub-61377
    - firebase deploy -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
