image: node

cache:
  paths:
    - node_modules/
  key: '$CI_BUILD_REPO'

stages:
  - develop
  - staging
  - deploy

develop:
  stage: deploy
  image: cortesa/docker-firebase
  environment: Production
  script:
    - npm install
    - npm run build
    - firebase use --token $FIREBASE_TOKEN syshub-dev
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
  except:
    - staging
    - master

staging:
  stage: staging
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
    - master

deploy:
  stage: deploy
  image: cortesa/docker-firebase
  environment: Production
  only:
    - staging
  script:
    - npm install
    - npm run build
    - firebase use --token $FIREBASE_TOKEN syshub-61377
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
