image: node

cache:
  paths:
  - node_modules/
  key: "$CI_BUILD_REPO"

stages:
  - develop
  - staging
  - deploy

develop:
  stage: develop
  image: ruby:latest
  script:
   - gem install dpl
   - dpl --provider=heroku --app=$HEROKU_APP_DEV --api-key=$HEROKU_API_KEY
  except:
   - staging
   - master
   - 62-aft-configure-gitlab-ci-to-deploy-master-branch-in-firebase-hosting

staging:
  stage: staging
  image: ruby:latest
  script:
   - gem install dpl
   - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  only:
   - staging

deploy:
  image: cortesa/docker-firebase
  stage: deploy
  script:
    - npm install
    - npm run build
    - firebase use syshub-61377 --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
  only:
    - master
    - 62-aft-configure-gitlab-ci-to-deploy-master-branch-in-firebase-hosting

