language: node_js
node_js:
  - '8.12'
cache:
  directories:
    - node_modules

before_script:
  - npm install --quite firebase-tools -g
  - firebase firebase --version

stages:
  - deploy Develop
  - name: deploy Stage
    if: branch = master

jobs:
  include:
    - stage: deploy Develop
      script:
        - yarn build:development
        - firebase use --token $FIREBASE_TOKEN syshub-dev
        - firebase deploy -m "Branch $TRAVIS_BRANCH, Commit $TRAVIS_COMMIT, Build $TRAVIS_BUILD_ID" --token $FIREBASE_TOKEN
    - stage: deploy Stage
      script:
        - yarn build:development
        - firebase use --token $FIREBASE_TOKEN syshub-dev
        - firebase deploy -m "Branch $TRAVIS_BRANCH, Commit $TRAVIS_COMMIT, Build $TRAVIS_BUILD_ID" --token $FIREBASE_TOKEN
