language: node_js
node_js:
  - '8.12'
cache:
  directories:
    - node_modules

before_install:
  - npm install --quite firebase-tools -g
  - firebase firebase --version
  - if [$TRAVIS_BRANCH = "master"]; then
    yarn build:development;
    fi

jobs:
  include:
    - stage: deployDev
      deploy:
        skip_cleanup: true
        provider: firebase
        token: $FIREBASE_TOKEN
        project: syshub-dev
        message: 'Travis, Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID'
