language: node_js
node_js:
  - '8.12'

branches:
  only:
    - master
    - production

cache:
  directories:
    - node_modules

before_script:
  - npm install --quite firebase-tools -g
  - firebase firebase --version

stages:
  - name: deploy Stage
    if: branch = master
  - name: deploy Production
    if: branch = production

jobs:
  include:
    - stage: deploy Stage
      script:
        - yarn build:development
        - firebase use --token $FIREBASE_TOKEN syshub-dev
        - firebase deploy -m "Branch $TRAVIS_BRANCH, Commit $TRAVIS_COMMIT, Build $TRAVIS_BUILD_ID" --token $FIREBASE_TOKEN
    - stage: deploy Production
      script:
        - yarn build
        - firebase use --token $FIREBASE_TOKEN syshub-61377
        - firebase deploy -m "Branch $TRAVIS_BRANCH, Commit $TRAVIS_COMMIT, Build $TRAVIS_BUILD_ID" --token $FIREBASE_TOKEN
