language: node_js
node_js:
  - '8.12'
cache:
  directories:
    - node_modules
before_install:
  - npm install --quite firebase-tools -g
  - firebase firebase --version
jobs:
  include:
    - stage: deployDev
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - yarn build:development
          - firebase use --token $FIREBASE_TOKEN syshub-dev
          - firebase deploy -m "Branch $TRAVIS_BRANCH, Commit $TRAVIS_COMMIT Build $TRAVIS_BUILD_ID" --token $FIREBASE_TOKEN
