language: node_js
node_js:
  - '8.12'
cache:
  directories:
    - node_modules

jods:
  include:
    - stage: add Firebase
      script:
        - npm install --quite firebase-tools -g
        - firebase firebase --version
    - stage: deploy
      script:
        - yarn build:development
        - firebase use --token $FIREBASE_TOKEN syshub-dev
        - firebase deploy -m "Travis, Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
