export default {
  // App States
  APP_USER_LOGIN: 'APP_USER_LOGIN',
  APP_USER_LOGOUT: 'APP_USER_LOGOUT',
  APP_LOADING_GLOBAL: 'APP_LOADING_GLOBAL',
  APP_PAGE_SHOW: 'APP_PAGE_SHOW',
  APP_CHAT_TOGGLE: 'APP_CHAT_TOGGLE',
  APP_MENU_TOGGLE: 'APP_MENU_TOGGLE',
  APP_PLATFORM_GET: 'APP_PLATFORM_GET',
  APP_PROPOSAL_CONTAINER: 'APP_PROPOSAL_CONTAINER',
  APP_PROPOSAL_SHOW: 'APP_PROPOSAL_SHOW',

  // MARTK Stats states
  MARTK_STATS_USER_GET: 'MARTK_STATS_USER_GET',
  MARTK_STATS_PRICE_GET: 'MARTK_STATS_PRICE_GET',
  MARTK_STATS_TMN_GET: 'MARTK_STATS_TMN_GET',
  MARTK_STATS_RMN_GET: 'MARTK_STATS_RMN_GET',

  // MARTK Proposals
  MARTK_PROPOSALS_GET: 'MARTK_PROPOSALS_GET',
  MARTK_PROPOSALS_CHECK: 'MARTK_PROPOSALS_CHECK',
  MARTK_PROPOSALS_PREPARE: 'MARTK_PROPOSALS_PREPARE',
  MARTK_PROPOSALS_SUBMIT: 'MARTK_PROPOSALS_SUBMIT',
  MARTK_PROPOSAL_VOTE: 'MARTK_PROPOSAL_VOTE',

  // MARTK Governance
  MARTK_GOVERNANCE_INFO: 'MARTK_GOVERNANCE_INFO',

  //2FA
  GET_2FA: 'GET_2FA',
  SET_2FA: 'SET_2FA',

  // MEDIUM Connect
  MEDIUM_POSTS_GET: 'MEDIUM_POSTS_GET'
};
